# Generated by Django 3.2.25 on 2026-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dvr',
        ),
        migrations.AddField(
            model_name='product',
            name='dvr',
            field=models.ManyToManyField(blank=True, related_name='products_dvr', to='store.DVRType'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='hdd',
        ),
        migrations.AddField(
            model_name='product',
            name='hdd',
            field=models.ManyToManyField(blank=True, related_name='products_with_hdd', to='store.HDDSize'),
        ),
    ]
