# Generated by Django 3.2.25 on 2026-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monitor_options/')),
            ],
        ),
        migrations.CreateModel(
            name='SMPSOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='smps_options/')),
            ],
        ),
        migrations.CreateModel(
            name='WireOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wire_options/')),
            ],
        ),
        migrations.AddField(
            model_name='dvrtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dvr_types/'),
        ),
        migrations.AddField(
            model_name='hddsize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hdd_sizes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='monitor',
            field=models.ManyToManyField(blank=True, related_name='products_with_monitor', to='store.MonitorOption'),
        ),
        migrations.AddField(
            model_name='product',
            name='smps',
            field=models.ManyToManyField(blank=True, related_name='products_with_smps', to='store.SMPSOption'),
        ),
        migrations.AddField(
            model_name='product',
            name='wire',
            field=models.ManyToManyField(blank=True, related_name='products_with_wire', to='store.WireOption'),
        ),
    ]
