# Generated by Django 3.2.25 on 2026-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productfeature_producthighlight_productspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvrtype',
            name='channels',
            field=models.PositiveIntegerField(blank=True, help_text='Number of camera channels, e.g. 4 for 4 Channel DVR', null=True),
        ),
    ]
