# Generated by Django 3.2.25 on 2026-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_dvrtype_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireoption',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
